print ("oackerrr")

return require("packer").startup(function()
    use("vijaymarupudi/nvim-fzf")
    use("tpope/vim-fugitive")
    use("tpope/vim-rhubarb")
    use("tpope/vim-sensible")
    use("junegunn/vim-easy-align")
    use("scrooloose/nerdtree")
    use("vim-airline/vim-airline")
    use("vim-airline/vim-airline-themes")
    use("google/vim-jsonnet")
    use("hashivim/vim-terraform")
    use("dag/vim-fish")
    use("neovim/nvim-lspconfig")
    use("nvim-lua/plenary.nvim")
    use("nvim-telescope/telescope.nvim")
    use("rust-lang/rust.vim")
    use("ellisonleao/glow.nvim")
    use("hrsh7th/cmp-nvim-lsp")
    use("hrsh7th/cmp-buffer")
    use("hrsh7th/cmp-path")
    use("hrsh7th/cmp-cmdline")
    use("hrsh7th/nvim-cmp")

end)
