local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {desc="Telescope Find files"})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {desc="Telescope Live grep"})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {desc="Telescope buffers"})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {desc="Telescope help"})
vim.keymap.set('n', '<leader>fd', "<cmd>Telescope diagnostics<cr>", {desc="Telescope diagnostics"})
